# Generated by Django 4.1.7 on 2023-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(default='example module', max_length=255),
        ),
    ]
